server:
  port: 9098
  servlet:
    context-path: /faraway

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springboot_teach_02?useUnicode=true&amp;characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

mybatis:
  type-aliases-package: com.sboot.study.entity
  mapper-locations: classpath:mapper/*.xml